version: "3"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=weather
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  app:
    build: ./
    image: "app:latest"
    ports:
      - 8085:8085
    depends_on:
      - mongodb
